[package]
name = "mentordl"
version = "1.0.0-beta.1"
edition = "2021"

[features]

[dependencies]
dirs = "4.0.0"
isahc = { version = "1.6.0", features = ["static-curl", "cookies"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = "1.0.131"
serde_derive = "1.0.131"
toml = "0.5.8"
url = "2.2.2"
